name: Update Fivem

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # allows manual trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.7.0

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: node scrape.js

      - name: Commit and push changes
        run: |
          git config user.name "Fivem Updater"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update fivem" || echo "No changes to commit"
          git push
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/fivem:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
